[package]
name = "little_devtools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "little_devtools"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.1"
chrono = "*"
random = "*"